### PR TITLE
Added default flag to customizable grid vars

### PR DESCRIPTION
**Pull request by andrewkamm**
This change makes grid vars that are intended to be customizable per-project overridable outside of this file by adding the [`!default` flag](http://j.mp/1q4MAiK) to them. This means users don't need to modify this file when they want custom values for their grid; instead, they can just define those variables in their Sass prior to importing `grid.scss` as a partial.

### CODE REVIEW

**Comment by cfree** [comment]
So in `style.scss` (which loads before `_grid.scss` is imported) we could define new variables that will override the ones set in `_grid.scss`?

Instead of `2.0.2-dev`, just bump the version to `2.0.3`. We use [git flow](http://nvie.com/posts/a-successful-git-branching-model/) to release products/libraries. We'll need to include this new version in the next Blueprint release as well.

**Comment by andrewkamm** [comment]
@cfree Correct. And if the vars don't get defined in `style.scss`, the ones in `_grid.scss` get used just like they would be now. This is useful in that it would (for example) allow sites to upgrade to a new version of css-grid without having to patch their own custom values back into it.

**Comment by andrewkamm** [comment]
Note that additional changes have been made on this branch since the original PR was issued:
- The min/max breakpoints used in the media query variables have been converted to stand-alone vars that can be used elsewhere (and of course, overridden).
- The breakpoint vars have been adjusted a bit, and now include `$sm-bp-min-width` and `$xs-bp-max-width`. 
- The existing media query vars have been renamed to match the size configs they correspond to (rather than a format name such as "desktop").
  - `$desktop-mq` is now `$lg-mq`
  - `$tablet-mq` is now `$md-mq` _(note: the default values put this as more of a desktop than a tablet)_
  - `$phone-mq` is now `$sm-mq` _(the default values put this as more of a tablet than a phone)_
- Since the "small" size (previously "phone") is actually targeted more at tablets, an additional media query var has been added for targeting phones: `$xs-mq`
- The usage of a couple media query vars defined within `grid.scss` has been changed to what I believe to be the actual intent of the original code. Specifically:
  - Styles previously applied using the `$tablet-mq` selector (since renamed to `$md-mq`), is now applied using `$sm-mq`. _(Reason: That section of code uses `$sm-` vars throughout and seems aimed at tablets, which based on the default values, would be selected by the `$sm-mq` selector. Also, the `$md-` vars were already being applied as the defaults (i.e., no specific media query))_
  - Styles previously applied using the `$phone-mq` selector (since renamed to `$sm-mq`), is now applied using `$xs-mq`.  _(Reason: That section of code is aimed at the smallest devices, not devices that would be targeted by the default values of the `$sm-` vars)_

**Comment by andrewkamm** [comment]
And a couple more changes before we merge this into develop:
- Max width of `$md-mq` (the "medium" media query) is only set if `$use-lg-breakpoint` is true
- Updated the `css/grid.css` generated file

**Pull request merged**
